# Generated by Django 5.0.1 on 2024-01-22 12:11

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='landImage',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_land.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[2878, 1618], upload_to='art_gallery/landscape'),
        ),
        migrations.AddField(
            model_name='image',
            name='squareImage',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_square.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 1000], upload_to='art_gallery/square'),
        ),
        migrations.AddField(
            model_name='image',
            name='tallImage',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_tall.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1618, 2878], upload_to='art_gallery/tall'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='art_gallery/'),
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.category'),
        ),
    ]
