# Generated by Django 5.0.1 on 2024-01-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_image_category_image_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='basic/art_gallery/'),
        ),
    ]
