# Generated by Django 5.0.1 on 2024-01-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_review_user_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='annonymous',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
