# Generated by Django 5.0.1 on 2024-01-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_review_annonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='annonymous',
            new_name='anonymous',
        ),
    ]
