# Generated by Django 5.0.1 on 2024-01-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_rename_annonymous_review_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rete',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
