# Generated by Django 5.0.1 on 2024-01-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_review_rete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rete',
            field=models.FloatField(default=2.5),
        ),
    ]
