# Generated by Django 5.0.1 on 2024-01-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_review_rete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rete',
            new_name='rate',
        ),
    ]
